$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:2
        },
        500:{
            items:4
        },
        800:{
            items:6
        },
        1000:{
            items:10
        }
    }
})